//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailNotifierClient.MailNotifierService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MailNotifierService.IMailNotifierService")]
    public interface IMailNotifierService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailNotifierService/FadeToRgb", ReplyAction="http://tempuri.org/IMailNotifierService/FadeToRgbResponse")]
        void FadeToRgb(byte red, byte green, byte blue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailNotifierService/FadeToMultiRgb", ReplyAction="http://tempuri.org/IMailNotifierService/FadeToMultiRgbResponse")]
        void FadeToMultiRgb(byte[] colorBytes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailNotifierService/SetColorRgb", ReplyAction="http://tempuri.org/IMailNotifierService/SetColorRgbResponse")]
        void SetColorRgb(byte red, byte green, byte blue);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMailNotifierServiceChannel : MailNotifierClient.MailNotifierService.IMailNotifierService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailNotifierServiceClient : System.ServiceModel.ClientBase<MailNotifierClient.MailNotifierService.IMailNotifierService>, MailNotifierClient.MailNotifierService.IMailNotifierService {
        
        public MailNotifierServiceClient() {
        }
        
        public MailNotifierServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailNotifierServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailNotifierServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailNotifierServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void FadeToRgb(byte red, byte green, byte blue) {
            base.Channel.FadeToRgb(red, green, blue);
        }
        
        public void FadeToMultiRgb(byte[] colorBytes) {
            base.Channel.FadeToMultiRgb(colorBytes);
        }
        
        public void SetColorRgb(byte red, byte green, byte blue) {
            base.Channel.SetColorRgb(red, green, blue);
        }
    }
}
