//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignTextClient.SignService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SignService.ISignService")]
    public interface ISignService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignService/ScrollText", ReplyAction="http://tempuri.org/ISignService/ScrollTextResponse")]
        void ScrollText(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignService/ScrollImage", ReplyAction="http://tempuri.org/ISignService/ScrollImageResponse")]
        void ScrollImage(bool[] imageData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignService/SetText", ReplyAction="http://tempuri.org/ISignService/SetTextResponse")]
        void SetText(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISignServiceChannel : SignTextClient.SignService.ISignService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignServiceClient : System.ServiceModel.ClientBase<SignTextClient.SignService.ISignService>, SignTextClient.SignService.ISignService {
        
        public SignServiceClient() {
        }
        
        public SignServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ScrollText(string text) {
            base.Channel.ScrollText(text);
        }
        
        public void ScrollImage(bool[] imageData) {
            base.Channel.ScrollImage(imageData);
        }
        
        public void SetText(string text) {
            base.Channel.SetText(text);
        }
    }
}
