//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TfsConsoleApplication.SignService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SignService.ISignService")]
    public interface ISignService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignService/SetText", ReplyAction="http://tempuri.org/ISignService/SetTextResponse")]
        void SetText(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignService/SetText", ReplyAction="http://tempuri.org/ISignService/SetTextResponse")]
        System.Threading.Tasks.Task SetTextAsync(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignService/SetImage", ReplyAction="http://tempuri.org/ISignService/SetImageResponse")]
        void SetImage(bool[] imageData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignService/SetImage", ReplyAction="http://tempuri.org/ISignService/SetImageResponse")]
        System.Threading.Tasks.Task SetImageAsync(bool[] imageData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISignServiceChannel : TfsConsoleApplication.SignService.ISignService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignServiceClient : System.ServiceModel.ClientBase<TfsConsoleApplication.SignService.ISignService>, TfsConsoleApplication.SignService.ISignService {
        
        public SignServiceClient() {
        }
        
        public SignServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetText(string text) {
            base.Channel.SetText(text);
        }
        
        public System.Threading.Tasks.Task SetTextAsync(string text) {
            return base.Channel.SetTextAsync(text);
        }
        
        public void SetImage(bool[] imageData) {
            base.Channel.SetImage(imageData);
        }
        
        public System.Threading.Tasks.Task SetImageAsync(bool[] imageData) {
            return base.Channel.SetImageAsync(imageData);
        }
    }
}
